/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fannog.proyectocliente.ui.modificarUs;

import java.time.LocalDate;

/**
 *
 * @author Rodrigo
 */
public class ModEst extends javax.swing.JPanel {

    /**
     * Creates new form ModUser
     */
    public ModEst() {
        initComponents();
    }

    public void setGeneracion(String generacion) {
        comboGeneracion.setSelectedItem(generacion);
    }
    
    public String getGeneracion() {
        String generacion = comboGeneracion.getSelectedItem().toString();
        return generacion;
    }

    public void populateComboGeneracion() {

        //List<String> generaciones = null;
        LocalDate current_date = LocalDate.now();
        int current_Year = current_date.getYear();

        for (int i = 2012; i <= current_Year; i++) {
            String año = String.valueOf(i);
            comboGeneracion.addItem(año);
            //generaciones.add(año);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        comboGeneracion = new javax.swing.JComboBox<>();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Generación");

        comboGeneracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboGeneracion.setPreferredSize(new java.awt.Dimension(64, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(comboGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(comboGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboGeneracion;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
